/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_2363f5d6 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/vsztquvvnwlxdwyeoffh/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Helper to check if table exists and handle gracefully
const handleError = (error: any, fallbackValue: any = null) => {
  // If table doesn't exist, return fallback value instead of throwing
  if (error && error.message && error.message.includes('kv_store_2363f5d6')) {
    console.warn('⚠️ KV Store table not found. Please run migration: /supabase/migrations/002_create_kv_store.sql');
    return fallbackValue;
  }
  if (error) {
    throw new Error(error.message);
  }
  return fallbackValue;
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_2363f5d6").upsert({
      key,
      value
    });
    handleError(error);
  } catch (err) {
    console.warn(`⚠️ KV Store set failed for key "${key}":`, err.message);
    // Silently fail - cache is optional
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  try {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_2363f5d6").select("value").eq("key", key).maybeSingle();
    handleError(error);
    return data?.value;
  } catch (err) {
    console.warn(`⚠️ KV Store get failed for key "${key}":`, err.message);
    return null; // Return null if cache unavailable
  }
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_2363f5d6").delete().eq("key", key);
    handleError(error);
  } catch (err) {
    console.warn(`⚠️ KV Store del failed for key "${key}":`, err.message);
    // Silently fail - cache is optional
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_2363f5d6").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
    handleError(error);
  } catch (err) {
    console.warn(`⚠️ KV Store mset failed for ${keys.length} keys:`, err.message);
    // Silently fail - cache is optional
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  try {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_2363f5d6").select("value").in("key", keys);
    handleError(error);
    return data?.map((d) => d.value) ?? [];
  } catch (err) {
    console.warn(`⚠️ KV Store mget failed for ${keys.length} keys:`, err.message);
    return []; // Return empty array if cache unavailable
  }
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_2363f5d6").delete().in("key", keys);
    handleError(error);
  } catch (err) {
    console.warn(`⚠️ KV Store mdel failed for ${keys.length} keys:`, err.message);
    // Silently fail - cache is optional
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  try {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_2363f5d6").select("key, value").like("key", prefix + "%");
    handleError(error);
    return data?.map((d) => d.value) ?? [];
  } catch (err) {
    console.warn(`⚠️ KV Store getByPrefix failed for prefix "${prefix}":`, err.message);
    return []; // Return empty array if cache unavailable
  }
};